# Generated by Django 2.2.6 on 2019-10-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='website_url',
            field=models.URLField(blank=True, default='https://onaway.ru/'),
        ),
    ]
