# Generated by Django 2.2.6 on 2019-11-01 20:41

from django.db import migrations, models
import user_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_auto_20191031_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='static/images/users/default_logo.png', upload_to=user_manager.models.get_image_path, verbose_name='Аватар'),
        ),
    ]
