# Generated by Django 2.2.6 on 2019-11-01 21:03

from django.db import migrations, models
import user_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_auto_20191101_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/images/users/default.png', upload_to=user_manager.models.get_image_path, verbose_name='Аватар'),
        ),
    ]
