# Generated by Django 2.2.6 on 2019-11-02 10:16

from django.db import migrations, models
import user_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_auto_20191102_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=models.CharField(choices=[('man', 'Мужской'), ('women', 'Женский')], default='man', max_length=5, verbose_name='Пол'), upload_to=user_manager.models.get_image_path, verbose_name='Аватар'),
        ),
    ]
