# Generated by Django 2.2.6 on 2019-11-02 10:19

from django.db import migrations, models
import user_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0006_auto_20191102_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/images/users/default_female.png', upload_to=user_manager.models.get_image_path, verbose_name='Аватар'),
        ),
    ]
