# Generated by Django 2.2.6 on 2019-11-01 12:01

from django.db import migrations, models
import travel_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_auto_20191101_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=travel_app.models.get_image_path),
        ),
    ]
