# Generated by Django 2.2.6 on 2019-11-01 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_app', '0006_auto_20191101_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trevel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.Travel', verbose_name='Путешествие')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
